### ISSUE TITLE
Validator is not called on configuration

### ISSUE THREAD

**Issue by ehibes** [BitBagCommerce/SyliusShippingExportPlugin#39]
Hi @bitbager, 

After completing the shipping gateway configuration, the validator service is not called to validate the configuration form even if it has contraints defined.
Is it normal or should it be fixed ?

**Comment by MacBalc** [comment]
@ehibes I would be happy to assist You. Can You share configuration example + ways constraints are applied?

**Comment by ehibes** [comment]
Hi @MacBalc, I made a provider for TNT carrier. Here is my gateway form : https://github.com/StudioWaaz/SyliusTntPlugin/blob/master/src/Form/Type/ShippingGatewayType.php

If I create a gateway without filling in any information, the gateway is still saved.

**Comment by MacBalc** [comment]
Maybe this problem is connected to validation configuration. I was able to get error messages displayed after setting up project (no config changed).
![image](https://github.com/BitBagCommerce/SyliusShippingExportPlugin/assets/124139291/22c72c99-67c2-43b8-bcc1-5a160806bd92) - could You please check if that maybe the case? If that will turn out to be uneffective i will be glad to dig a bit further :)

**Comment by ehibes** [comment]
I found, I have to put the group 'bitbag' on the constraints to be called by the validator. It's on README, so my fault.
Thanks @MacBalc
